ERROR 2022-09-27 22:55:27,319 log 13820 10716 Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\admin\sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\generic\base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\generic\base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\generic\edit.py", line 152, in post
    if form.is_valid():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\forms\forms.py", line 205, in is_valid
    return self.is_bound and not self.errors
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\forms\forms.py", line 200, in errors
    self.full_clean()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\forms\forms.py", line 438, in full_clean
    self._clean_form()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\forms\forms.py", line 459, in _clean_form
    cleaned_data = self.clean()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\forms.py", line 217, in clean
    self.user_cache = authenticate(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\debug.py", line 42, in sensitive_variables_wrapper
    return func(*func_args, **func_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\__init__.py", line 77, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\base_user.py", line 46, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 646, in get
    num = len(clone)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 376, in __len__
    self._fetch_all()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 87, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 1382, in execute_sql
    sql, params = self.as_sql()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 590, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 71, in pre_sql_setup
    self.setup_query()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 62, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 291, in get_select
    sql, params = self.compile(col)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 503, in compile
    sql, params = node.as_sql(self, self.connection)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\expressions.py", line 1110, in as_sql
    sql = ".".join(map(compiler.quote_name_unless_alias, identifiers))
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 494, in quote_name_unless_alias
    r = self.connection.ops.quote_name(name)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\dummy\base.py", line 20, in complain
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: settings.DATABASES is improperly configured. Please supply the ENGINE value. Check settings documentation for more details.
ERROR 2022-09-27 22:55:27,349 basehttp 13820 10716 "POST /admin/login/?next=/admin/ HTTP/1.1" 500 238751
WARNING 2022-09-28 20:13:21,185 log 9064 2868 Not Found: /
WARNING 2022-09-28 20:13:21,185 basehttp 9064 2868 "GET / HTTP/1.1" 404 12228
WARNING 2022-09-28 20:13:21,350 log 9064 12884 Not Found: /favicon.ico
WARNING 2022-09-28 20:13:21,351 basehttp 9064 12884 "GET /favicon.ico HTTP/1.1" 404 12289
WARNING 2022-09-28 21:36:20,134 log 1752 11500 Not Found: /users/
WARNING 2022-09-28 21:36:20,135 basehttp 1752 11500 "GET /users/ HTTP/1.1" 404 12427
WARNING 2022-09-28 21:36:37,656 log 2188 11060 Not Found: /users/
WARNING 2022-09-28 21:36:37,657 basehttp 2188 11060 "GET /users/ HTTP/1.1" 404 12589
ERROR 2022-09-28 21:36:42,126 log 2188 11060 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:36:42,168 basehttp 2188 11060 "GET /users/register/ HTTP/1.1" 500 132305
ERROR 2022-09-28 21:38:59,842 log 4956 9828 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:38:59,878 basehttp 4956 9828 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:40:11,644 log 4956 9828 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:40:11,675 basehttp 4956 9828 "GET /users/register/ HTTP/1.1" 500 132441
ERROR 2022-09-28 21:40:55,167 log 4536 1156 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:40:55,216 basehttp 4536 1156 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:41:42,219 log 10568 4528 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:41:42,258 basehttp 10568 4528 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:41:43,502 log 10568 4528 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:41:43,535 basehttp 10568 4528 "GET /users/register/ HTTP/1.1" 500 132441
ERROR 2022-09-28 21:41:56,487 log 9864 12372 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:41:56,528 basehttp 9864 12372 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:42:07,081 log 7584 6748 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:42:07,122 basehttp 7584 6748 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:43:28,264 log 3448 12916 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:43:28,305 basehttp 3448 12916 "GET /users/register/ HTTP/1.1" 500 132442
ERROR 2022-09-28 21:43:29,089 log 3448 12916 Internal Server Error: /users/register/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 723, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 654, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\renderers.py", line 562, in get_raw_data_form
    data = serializer.data.copy()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 555, in data
    ret = super().data
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 257, in data
    self._data = self.get_initial()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 405, in get_initial
    for field in self.fields.values()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 356, in fields
    for key, value in self.get_fields().items():
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 1051, in get_fields
    info = model_meta.get_field_info(model)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\utils\model_meta.py", line 35, in get_field_info
    opts = model._meta.concrete_model._meta
AttributeError: 'str' object has no attribute '_meta'
ERROR 2022-09-28 21:43:29,116 basehttp 3448 12916 "GET /users/register/ HTTP/1.1" 500 132441
WARNING 2022-09-28 21:43:34,188 log 6076 12416 Method Not Allowed: /users/register/
WARNING 2022-09-28 21:43:34,189 basehttp 6076 12416 "GET /users/register/ HTTP/1.1" 405 18434
WARNING 2022-09-28 21:44:12,615 log 6076 9624 Bad Request: /users/register/
WARNING 2022-09-28 21:44:12,616 basehttp 6076 9624 "POST /users/register/ HTTP/1.1" 400 18564
WARNING 2022-09-28 21:44:23,827 log 6076 9624 Bad Request: /users/register/
WARNING 2022-09-28 21:44:23,828 basehttp 6076 9624 "POST /users/register/ HTTP/1.1" 400 18588
WARNING 2022-09-28 21:44:29,453 log 6076 9624 Bad Request: /users/register/
WARNING 2022-09-28 21:44:29,454 basehttp 6076 9624 "POST /users/register/ HTTP/1.1" 400 18591
WARNING 2022-09-28 21:45:09,132 log 6076 9624 Not Found: /users/login/
WARNING 2022-09-28 21:45:09,132 basehttp 6076 9624 "GET /users/login/ HTTP/1.1" 404 12613
WARNING 2022-09-28 21:45:15,402 log 6076 9624 Not Found: /users/auth
WARNING 2022-09-28 21:45:15,403 basehttp 6076 9624 "GET /users/auth HTTP/1.1" 404 12605
WARNING 2022-09-28 21:45:17,863 log 6076 9624 Not Found: /users/auth/
WARNING 2022-09-28 21:45:17,864 basehttp 6076 9624 "GET /users/auth/ HTTP/1.1" 404 13911
WARNING 2022-09-28 21:45:20,864 log 6076 9624 Method Not Allowed: /users/auth/login/
WARNING 2022-09-28 21:45:20,865 basehttp 6076 9624 "GET /users/auth/login/ HTTP/1.1" 405 17761
WARNING 2022-09-28 21:47:13,309 log 6076 9624 Not Found: /
WARNING 2022-09-28 21:47:13,310 basehttp 6076 9624 "GET / HTTP/1.1" 404 12333
WARNING 2022-09-28 21:47:29,792 log 6076 9624 Method Not Allowed: /users/auth/logout/
WARNING 2022-09-28 21:47:29,793 basehttp 6076 9624 "GET /users/auth/logout/ HTTP/1.1" 405 16754
WARNING 2022-09-28 21:50:14,441 log 6076 9624 Method Not Allowed: /users/auth/logout/
WARNING 2022-09-28 21:50:14,442 basehttp 6076 9624 "GET /users/auth/logout/ HTTP/1.1" 405 16789
WARNING 2022-09-28 21:50:20,772 log 6076 9624 Method Not Allowed: /users/auth/logout/
WARNING 2022-09-28 21:50:20,773 basehttp 6076 9624 "GET /users/auth/logout/ HTTP/1.1" 405 16789
WARNING 2022-09-28 21:50:45,219 log 6076 9624 Method Not Allowed: /users/auth/logout/
WARNING 2022-09-28 21:50:45,220 basehttp 6076 9624 "GET /users/auth/logout/ HTTP/1.1" 405 16789
WARNING 2022-09-28 21:51:06,788 log 6076 9624 Method Not Allowed: /users/auth/logout/
WARNING 2022-09-28 21:51:06,788 basehttp 6076 9624 "GET /users/auth/logout/ HTTP/1.1" 405 16754
WARNING 2022-09-28 21:51:10,784 log 6076 9624 Not Found: /users/auth/
WARNING 2022-09-28 21:51:10,784 basehttp 6076 9624 "GET /users/auth/ HTTP/1.1" 404 13911
WARNING 2022-09-28 22:24:20,286 log 6480 4624 Method Not Allowed: /users/register/
WARNING 2022-09-28 22:24:20,287 basehttp 6480 4624 "GET /users/register/ HTTP/1.1" 405 18434
WARNING 2022-09-28 22:24:32,945 log 6480 4624 Bad Request: /users/register/
WARNING 2022-09-28 22:24:32,946 basehttp 6480 4624 "POST /users/register/ HTTP/1.1" 400 18590
WARNING 2022-09-28 22:47:39,662 log 11700 11060 Not Found: /users/login/
WARNING 2022-09-28 22:47:39,663 basehttp 11700 11060 "GET /users/login/ HTTP/1.1" 404 12613
WARNING 2022-09-28 22:47:45,545 log 11700 9184 Method Not Allowed: /users/auth/login/
WARNING 2022-09-28 22:47:45,546 basehttp 11700 9184 "GET /users/auth/login/ HTTP/1.1" 405 17761
WARNING 2022-09-29 20:05:55,140 log 2128 12344 Not Found: /
WARNING 2022-09-29 20:05:55,150 basehttp 2128 12344 "GET / HTTP/1.1" 404 12334
WARNING 2022-09-29 20:05:55,262 log 2128 5032 Not Found: /favicon.ico
WARNING 2022-09-29 20:05:55,262 basehttp 2128 5032 "GET /favicon.ico HTTP/1.1" 404 12395
WARNING 2022-09-29 20:40:51,880 log 4632 12220 Not Found: /
WARNING 2022-09-29 20:40:51,881 basehttp 4632 12220 "GET / HTTP/1.1" 404 12333
WARNING 2022-09-29 20:41:18,644 log 4632 12220 Not Found: /
WARNING 2022-09-29 20:41:18,644 basehttp 4632 12220 "GET / HTTP/1.1" 404 12333
WARNING 2022-09-29 20:58:48,799 log 14048 1320 Unauthorized: /flight/flights/
WARNING 2022-09-29 20:58:48,800 basehttp 14048 1320 "GET /flight/flights/ HTTP/1.1" 401 27
WARNING 2022-09-29 20:59:32,563 log 14048 1320 Not Found: /flight/flights/2/
WARNING 2022-09-29 20:59:32,564 basehttp 14048 1320 "GET /flight/flights/2/ HTTP/1.1" 404 23
WARNING 2022-09-29 20:59:43,027 log 14048 1320 Not Found: /flight/flight/1
WARNING 2022-09-29 20:59:43,027 basehttp 14048 1320 "GET /flight/flight/1 HTTP/1.1" 404 13630
WARNING 2022-09-29 21:27:42,688 log 15808 13476 Forbidden: /flight/flights/
WARNING 2022-09-29 21:27:42,689 basehttp 15808 13476 "POST /flight/flights/ HTTP/1.1" 403 63
WARNING 2022-09-29 21:28:16,086 log 15808 13476 Unauthorized: /flight/flights/
WARNING 2022-09-29 21:28:16,087 basehttp 15808 13476 "GET /flight/flights/ HTTP/1.1" 401 58
WARNING 2022-09-29 21:28:54,678 log 15808 13476 Forbidden: /flight/flights/
WARNING 2022-09-29 21:28:54,679 basehttp 15808 13476 "GET /flight/flights/ HTTP/1.1" 403 63
WARNING 2022-09-29 21:33:48,620 log 13292 10508 Forbidden: /flight/flights/
WARNING 2022-09-29 21:33:48,621 basehttp 13292 10508 "POST /flight/flights/ HTTP/1.1" 403 63
WARNING 2022-09-29 22:19:28,534 log 12684 8600 Unsupported Media Type: /flight/resv/
WARNING 2022-09-29 22:19:28,535 basehttp 12684 8600 "POST /flight/resv/ HTTP/1.1" 415 62
WARNING 2022-09-29 22:20:06,292 log 12684 8600 Unsupported Media Type: /flight/resv/
WARNING 2022-09-29 22:20:06,293 basehttp 12684 8600 "POST /flight/resv/ HTTP/1.1" 415 62
WARNING 2022-09-29 22:21:05,373 log 12684 8600 Bad Request: /flight/resv/
WARNING 2022-09-29 22:21:05,374 basehttp 12684 8600 "POST /flight/resv/ HTTP/1.1" 400 39
WARNING 2022-09-29 22:21:44,398 log 9988 4316 Bad Request: /flight/resv/
WARNING 2022-09-29 22:21:44,399 basehttp 9988 4316 "POST /flight/resv/ HTTP/1.1" 400 39
WARNING 2022-09-29 22:29:48,605 log 7780 6480 Bad Request: /flight/resv/
WARNING 2022-09-29 22:29:48,605 basehttp 7780 6480 "POST /flight/resv/ HTTP/1.1" 400 39
WARNING 2022-09-29 22:30:13,685 log 9588 15992 Bad Request: /flight/resv/
WARNING 2022-09-29 22:30:13,686 basehttp 9588 15992 "POST /flight/resv/ HTTP/1.1" 400 39
ERROR 2022-09-29 22:32:05,998 log 3592 2008 Internal Server Error: /flight/resv/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_passenger.update_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\flight\serializers.py", line 51, in create
    pas = Passenger.objects.create(**passenger)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 154, in _record
    return method(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_passenger.update_date
ERROR 2022-09-29 22:32:06,076 basehttp 3592 2008 "POST /flight/resv/ HTTP/1.1" 500 227264
ERROR 2022-09-29 22:32:41,069 log 608 3036 Internal Server Error: /flight/resv/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: flight_passenger.update_date

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 19, in create
    self.perform_create(serializer)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 24, in perform_create
    serializer.save()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\flight\serializers.py", line 51, in create
    pas = Passenger.objects.create(**passenger)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 831, in save
    self.save_base(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 882, in save_base
    updated = self._save_table(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 1025, in _save_table
    results = self._do_insert(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\base.py", line 1066, in _do_insert
    return manager._insert(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\compiler.py", line 1657, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 230, in execute
    return self._record(self.cursor.execute, sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\debug_toolbar\panels\sql\tracking.py", line 154, in _record
    return method(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 357, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: flight_passenger.update_date
ERROR 2022-09-29 22:32:41,139 basehttp 608 3036 "POST /flight/resv/ HTTP/1.1" 500 227264
ERROR 2022-09-29 22:40:11,221 log 7536 10128 Internal Server Error: /flight/resv/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\flight\views.py", line 20, in get_queryset
    return queryset.filter(user=self.request.user)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000014838ABD360>.
ERROR 2022-09-29 22:40:11,262 basehttp 7536 10128 "GET /flight/resv/ HTTP/1.1" 500 168062
ERROR 2022-09-29 22:42:04,081 log 12684 15480 Internal Server Error: /flight/resv/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\flight\views.py", line 26, in get_queryset
    return queryset.filter(user=self.request.user)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000017679658880>.
ERROR 2022-09-29 22:42:04,121 basehttp 12684 15480 "GET /flight/resv/ HTTP/1.1" 500 168062
ERROR 2022-09-29 22:42:49,184 log 12684 1968 Internal Server Error: /flight/resv/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2018, in get_prep_value
    return int(value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\contrib\auth\models.py", line 437, in __int__
    raise TypeError(
TypeError: Cannot cast AnonymousUser to int. Are you trying to use it in place of User?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\flight\views.py", line 26, in get_queryset
    return queryset.filter(user=self.request.user)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1420, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1438, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 1445, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1532, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1562, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1478, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\sql\query.py", line 1303, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\related_lookups.py", line 166, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\fields\__init__.py", line 2020, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <django.contrib.auth.models.AnonymousUser object at 0x0000017679A906A0>.
ERROR 2022-09-29 22:42:49,211 basehttp 12684 1968 "GET /flight/resv/ HTTP/1.1" 500 23241
WARNING 2022-09-29 22:56:47,632 log 3460 10428 Forbidden: /flight/flights/
WARNING 2022-09-29 22:56:47,633 basehttp 3460 10428 "POST /flight/flights/ HTTP/1.1" 403 63
WARNING 2022-09-29 23:00:00,779 log 3460 10428 Method Not Allowed: /flight/resv/
WARNING 2022-09-29 23:00:00,780 basehttp 3460 10428 "DELETE /flight/resv/ HTTP/1.1" 405 43
WARNING 2022-09-29 23:00:20,540 log 3460 10428 Method Not Allowed: /flight/resv/
WARNING 2022-09-29 23:00:20,541 basehttp 3460 10428 "DELETE /flight/resv/ HTTP/1.1" 405 43
WARNING 2022-09-29 23:10:58,608 log 6812 9168 Bad Request: /flight/resv/
WARNING 2022-09-29 23:10:58,608 basehttp 6812 9168 "POST /flight/resv/ HTTP/1.1" 400 41
WARNING 2022-09-29 23:11:23,103 log 6812 12268 Not Found: /flight/flight
WARNING 2022-09-29 23:11:23,103 basehttp 6812 12268 "GET /flight/flight HTTP/1.1" 404 14472
ERROR 2022-09-29 23:11:40,628 log 6812 12268 Internal Server Error: /flight/flights/3/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 632, in get
    raise NotSupportedError(
django.db.utils.NotSupportedError: Calling QuerySet.get(...) with filters after union() is not supported.
ERROR 2022-09-29 23:11:40,661 basehttp 6812 12268 "GET /flight/flights/3/ HTTP/1.1" 500 126733
ERROR 2022-09-29 23:11:43,521 log 6812 12268 Internal Server Error: /flight/flights/2/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 632, in get
    raise NotSupportedError(
django.db.utils.NotSupportedError: Calling QuerySet.get(...) with filters after union() is not supported.
ERROR 2022-09-29 23:11:43,597 basehttp 6812 12268 "GET /flight/flights/2/ HTTP/1.1" 500 126734
ERROR 2022-09-29 23:11:46,024 log 6812 12268 Internal Server Error: /flight/flights/1/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 632, in get
    raise NotSupportedError(
django.db.utils.NotSupportedError: Calling QuerySet.get(...) with filters after union() is not supported.
ERROR 2022-09-29 23:11:46,065 basehttp 6812 12268 "GET /flight/flights/1/ HTTP/1.1" 500 126733
ERROR 2022-09-29 23:12:19,191 log 6812 12268 Internal Server Error: /flight/flights/3/
Traceback (most recent call last):
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\mixins.py", line 54, in retrieve
    instance = self.get_object()
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 96, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "C:\Users\abdul\OneDrive\Masaüstü\Flight Project\env\lib\site-packages\django\db\models\query.py", line 632, in get
    raise NotSupportedError(
django.db.utils.NotSupportedError: Calling QuerySet.get(...) with filters after union() is not supported.
ERROR 2022-09-29 23:12:19,222 basehttp 6812 12268 "GET /flight/flights/3/ HTTP/1.1" 500 21409
WARNING 2022-09-29 23:12:31,860 log 6812 12268 Not Found: /
WARNING 2022-09-29 23:12:31,861 basehttp 6812 12268 "GET / HTTP/1.1" 404 12440
WARNING 2022-09-30 21:48:42,373 log 7760 8088 Not Found: /
WARNING 2022-09-30 21:48:42,392 basehttp 7760 8088 "GET / HTTP/1.1" 404 12441
WARNING 2022-09-30 21:48:42,522 log 7760 10696 Not Found: /favicon.ico
WARNING 2022-09-30 21:48:42,523 basehttp 7760 10696 "GET /favicon.ico HTTP/1.1" 404 12502
